SUPABASE_URL = "https://vgzcntdomncpokafurnb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnemNudGRvbW5jcG9rYWZ1cm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMTgxODksImV4cCI6MjA3OTY5NDE4OX0.RSavQIACgva6yWfbCVaH7we7RRuQA8ohWqeyWQiJ4_A"
