SUPABASE_URL = "https://wlrtrnfcepjpuegnqgjv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndscnRybmZjZXBqcHVlZ25xZ2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxMjc2NjAsImV4cCI6MjA3OTcwMzY2MH0._iTSSaYlcdtHTvkz3K-M-iri9R-NN0Z0RbNam8SFevQ"
